name: bayt
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc_concurrency: ^0.1.0
  bot_toast: ^4.0.1
  dio: ^4.0.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter_bloc: ^7.3.0
  flutter_translate: ^3.0.1
  flutter_translate_annotations: ^2.0.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_translate_gen: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/logo.png